' このファイルは、このプロジェクトに適用される SuppressMessage 
'属性を保持するために、コード分析によって使用されます。
' プロジェクト レベルの抑制には、ターゲットがないものと、特定のターゲット
'が指定され、名前空間、型、メンバーなどをスコープとするものがあります。
'
' このファイルに抑制を追加するには、[エラー一覧] でメッセージを
'右クリックし、[メッセージの非表示] をポイントして、
'[プロジェクト抑制ファイル内] をクリックします。
' このファイルに手動で抑制を追加する必要はありません。


<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetContractCarVinDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202BookedAfterProcessDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202SourcesOfACardMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202SalesInfoDetailDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202RequestIDAttractIDBySalesIDDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetContractCarDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetBookedAfterDetailInfoStatusDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetBookedAfterDetailInfoDateDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetBookedAfterDetailInfoDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202BrandRecognitionMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetProcessAfterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202UpdateSelectedCompeFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202UpdateSelectedVclCountFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202UpdateSelectedSeriesFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202UpdateSalesMemoFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202UpdateSalesConditionFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetStatusToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetStatusFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetStatusDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSeriesMasterToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSeriesMasterFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSeriesMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSeqnoToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedSeriesNoToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedSeriesNoDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedSeriesListToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedSeriesListFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedSeriesDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedCompeListToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedCompeListFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedCompeDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesMemoTodayToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesMemoTodayFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesMemoTodayDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesMemoListDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesMemoHisToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesMemoHisFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesConditionToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesConditionTitleDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesConditionMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesConditionItemDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesConditionFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesConditionDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetProcessToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetProcessFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetProcessDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetModelMasterToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetModelMasterFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetModelMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetFollowupboxListDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetFollowupboxDetailDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetFllwupboxNoToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetFllwupboxNoDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetFllwupboxContentDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetEstimateidToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetEstimateidFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetCompeModelMasterToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetCompeModelMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetCompeMakerMasterToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetCompeMakerMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetColorMasterToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetColorMasterFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetColorMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetCategoryCountDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetActivityListToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetActivityListFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetActivityDetailToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetActivityDetailFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetActivityDetailToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202UpdateSelectedSeriesFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202UpdateSelectedVclCountFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202UpdateSelectedCompeFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202UpdateSalesMemoFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202UpdateSalesConditionFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetStatusToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetStatusFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetStatusDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSeriesMasterToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSeriesMasterFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSeriesMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSeqnoToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedSeriesNoToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedSeriesNoDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedSeriesListToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedSeriesListFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedSeriesDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedCompeListToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedCompeListFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSelectedCompeDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesMemoTodayToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesMemoTodayFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesMemoTodayDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesMemoListDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesMemoHisToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesMemoHisFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesConditionToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesConditionTitleDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesConditionMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesConditionItemDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesConditionFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetSalesConditionDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetProcessToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetProcessFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetProcessDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetModelMasterToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetModelMasterFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetModelMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetFollowupboxListDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetFollowupboxDetailDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetFllwupboxNoToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetFllwupboxNoDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetFllwupboxContentDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetEstimateidToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetEstimateidFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetCompeModelMasterToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetCompeModelMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetCompeMakerMasterToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetCompeMakerMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetColorMasterToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetColorMasterFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetColorMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetCategoryCountDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetActivityListToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetActivityListFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202GetActivityDetailFromDataTable")> 

'0005
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="Cd", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202TableAdapter.#GetContractCarDataVin(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202RequestIDAttractIDBySalesIDRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202DataSet+SC3080202RequestIDAttractIDBySalesIDDataTable")> 

'0043
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202TableAdapter.#GetSelectedSeriesSeqno()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202TableAdapter.#GetSelectedCompeModelMaster()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202TableAdapter.#GetSelectedCompeMakerMaster()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202TableAdapter.#GetSalesConditionMaster()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202TableAdapter.#GetProcessIcons()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202TableAdapter.#GetFllwupboxSeqno()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080202TableAdapter.#GetBrandRecognitionMaster()")> 

'0004
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess")> 


