'
'
' このファイルは、このプロジェクトに適用される SuppressMessage 
'属性を保持するために、コード分析によって使用されます。
' プロジェクト レベルの抑制には、ターゲットがないものと、特定のターゲット
'が指定され、名前空間、型、メンバーなどをスコープとするものがあります。
'
' このファイルに抑制を追加するには、[エラー一覧] でメッセージを
'右クリックし、[メッセージの非表示] をポイントして、
'[プロジェクト抑制ファイル内] をクリックします。
' このファイルに手動で抑制を追加する必要はありません。


<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1809:AvoidExcessiveLocals", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#InsertActivityData(Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoRegistDataDataTable,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1809:AvoidExcessiveLocals", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#UpdateActivityData(Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoRegistDataDataTable,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#UpdateActivityData(Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoRegistDataDataTable,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#InsertActivityData(Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoRegistDataDataTable,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope:="type", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#UpdateActivityData(Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoRegistDataDataTable,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#InsertActivityData(Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoRegistDataDataTable,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#GetProcess(Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetProcessFromDataTable)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#InsertActivityData(Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoRegistDataDataTable,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#UpdateActivityData(Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoRegistDataDataTable,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.CommonUtility.BizLogic")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#GetUsers()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#GetDateFormat()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#SetToDo(Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoRegistDataDataTable,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#GetProcess(Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetProcessFromDataTable)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#GetEstimateDate(Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetContractDateFromDataTable)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#ACTIONCD_CATALOG")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#ACTIONCD_EVALUATION")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#ACTIONCD_QUOTATION")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#ACTIONCD_TESTDRIVE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#CRACTRESULT_SUCCESS")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#SALESAFTER_NO")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#SALESAFTER_YES")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#UpdateFllwupboxSales(System.String,System.String,System.Int64,System.String,System.DateTime,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#WAITINGOBJECT_ALLOCATION")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#WAITINGOBJECT_DELIVERY")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#WAITINGOBJECT_PAYMENT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#WAITINGOBJECT_SUCCESS")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="WAITINGOBJECT", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#WAITINGOBJECT_SUCCESS")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SUCCESS", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#WAITINGOBJECT_SUCCESS")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="WAITINGOBJECT", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#WAITINGOBJECT_PAYMENT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="PAYMENT", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#WAITINGOBJECT_PAYMENT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="WAITINGOBJECT", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#WAITINGOBJECT_DELIVERY")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DELIVERY", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#WAITINGOBJECT_DELIVERY")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="WAITINGOBJECT", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#WAITINGOBJECT_ALLOCATION")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ALLOCATION", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#WAITINGOBJECT_ALLOCATION")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="seqno", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#UpdateFllwupboxSales(System.String,System.String,System.Int64,System.String,System.DateTime,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="YES", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#SALESAFTER_YES")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SALESAFTER", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#SALESAFTER_YES")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SALESAFTER", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#SALESAFTER_NO")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SUCCESS", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#CRACTRESULT_SUCCESS")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRACTRESULT", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#CRACTRESULT_SUCCESS")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACTIONCD", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#ACTIONCD_TESTDRIVE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TESTDRIVE", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#ACTIONCD_TESTDRIVE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="QUOTATION", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#ACTIONCD_QUOTATION")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACTIONCD", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#ACTIONCD_QUOTATION")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="EVALUATION", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#ACTIONCD_EVALUATION")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACTIONCD", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#ACTIONCD_EVALUATION")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CATALOG", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#ACTIONCD_CATALOG")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACTIONCD", Scope:="member", Target:="Toyota.eCRB.CommonUtility.BizLogic.ActivityInfoBusinessLogic.#ACTIONCD_CATALOG")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.CommonUtility.BizLogic")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.CommonUtility.BizLogic")> 

