'
'
' このファイルは、このプロジェクトに適用される SuppressMessage 
'属性を保持するために、コード分析によって使用されます。
' プロジェクト レベルの抑制には、ターゲットがないものと、特定のターゲット
'が指定され、名前空間、型、メンバーなどをスコープとするものがあります。
'
' このファイルに抑制を追加するには、[エラー一覧] でメッセージを
'右クリックし、[メッセージの非表示] をポイントして、
'[プロジェクト抑制ファイル内] をクリックします。
' このファイルに手動で抑制を追加する必要はありません。







<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="MANAGEMENT", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_SERVICE_VISIT_MANAGEMENTDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SERVICE", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_SERVICE_VISIT_MANAGEMENTDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TBL", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_SERVICE_VISIT_MANAGEMENTDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="VISIT", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_SERVICE_VISIT_MANAGEMENTDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_SERVICE_VISIT_MANAGEMENTDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_SERVICE_VISIT_MANAGEMENTDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="MANAGEMENT", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_SERVICE_VISIT_MANAGEMENTRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SERVICE", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_SERVICE_VISIT_MANAGEMENTRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TBL", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_SERVICE_VISIT_MANAGEMENTRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="VISIT", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_SERVICE_VISIT_MANAGEMENTRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_SERVICE_VISIT_MANAGEMENTRow")> 
'1276
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.Logger.#Error(System.String,System.Exception)")> 
'0014
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+STATUS_MACADDRESSDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+STATUS_MACADDRESSRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+STATUS_MACADDRESSDataTable")> 
'0056
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.ConnectionManager.#OpenConnection(Toyota.eCRB.SystemFrameworks.Core.DBQueryTarget)")> 
'0022
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="1", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.OracleExceptionEx.#.ctor(Oracle.DataAccess.Client.OracleException,Oracle.DataAccess.Client.OracleCommand)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="0", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.OracleExceptionEx.#.ctor(Oracle.DataAccess.Client.OracleException,Oracle.DataAccess.Client.OracleCommand)")> 
'0025
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.EnvironmentSetting.#LoginUrl")> 
'0023
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.SystemConfiguration.#Hooks")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.UsersTableAdapter.#GetUsersDataTable(System.String,System.String,System.Collections.Generic.List`1<System.Decimal>,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Users.#GetAllUser(System.String,System.String,System.Collections.Generic.List`1<System.Decimal>,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.OperationTypeTableAdapter.#GetOperationTypeDataTable(System.String,System.String,System.Collections.Generic.List`1<System.Decimal>,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.OperationType.#GetAllOperationType(System.String,System.Collections.Generic.List`1<System.Decimal>,System.String)")> 
'0019
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Branch.#GetAllBranch(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Users.#GetUser(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Users.#GetAllUser(System.String,System.String,System.Collections.Generic.List`1<System.Decimal>,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.OperationType.#GetOperationType(System.String,System.Decimal,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.OperationType.#GetAllOperationType(System.String,System.Collections.Generic.List`1<System.Decimal>,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.Logger.#Info(System.String,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.Logger.#Error(System.String,System.Exception)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Dealer.#GetDealer(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Dealer.#GetAllDealer(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.DBUpdateQuery.#.ctor(System.String,Toyota.eCRB.SystemFrameworks.Core.DBQueryTarget)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.DBUpdateQuery.#Execute(System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.DBSelectQuery`1.#.ctor(System.String,Toyota.eCRB.SystemFrameworks.Core.DBQueryTarget)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.DBSelectQuery`1.#GetData(System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.DBSelectQuery`1.#GetCount(System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.DateTimeFunc.#Now(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.DateTimeFunc.#FormatElapsedDate(Toyota.eCRB.SystemFrameworks.Core.ElapsedDateFormat,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.DateTimeFunc.#FormatDate(System.Int32,System.DateTime,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Branch.#GetBranch(System.String,System.String,System.String)")> 

<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="MACADDRESS", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+STATUS_MACADDRESSDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="MACADDRESS", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+STATUS_MACADDRESSRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="STATUS", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+STATUS_MACADDRESSDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="STATUS", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+STATUS_MACADDRESSRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SVR", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#SVR")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SSV", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#SSV")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SLR", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#SLR")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ABR", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#ABR")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="AHO", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#AHO")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId:="Login", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerTableAdapter.#GetLoginTimeData(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="net", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.LoggerUtility.#Setlog4netSettingPrameter(System.String,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DMS", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.SystemConfigurationType.#DMSConnectionString")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DMS", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.DBQueryTarget.#DMS")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="c", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerTableAdapter.#GetClientIPData(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerTableAdapter.#GetClientIPData(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.IcropWordTableAdapter.#GetDefaultWordTable()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.IcropWordTableAdapter.#GetDealerWordTable()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemSharedDataSetTableAdapters.SystemSharedTableAdapter.#GetDateTimeForm()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.IcropWordDataSetTableAdapters.IcropWordTableTableAdapter.#GetDefaultWordTable()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemSharedDataSetTableAdapters.DateTimeFormTableTableAdapter.#GetDateTimeForm()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.IcropWordDataSetTableAdapters.IcropWordTableTableAdapter.#GetDealerWordTable()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters.TBL_CLIENT_IPTableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters.TBL_CLIENT_MACADDRESSTableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSetTableAdapters.TBL_DATETIMEFORMTableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters.TBL_CLIENT_IPTableAdapter.#GetData(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ASB", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#ASB")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ASH", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#ASH")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="BPS", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#BPS")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="BRANCH", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchDataSet+BRANCHDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="BRANCH", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchDataSet+BRANCHRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="c", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters.TBL_CLIENT_IPTableAdapter.#GetData(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CCM", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#CCM")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CCO", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#CCO")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CLIENT", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters.TBL_CLIENT_IPTableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CLIENT", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters.TBL_CLIENT_MACADDRESSTableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CSB", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#CSB1")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CSB", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#CSB2")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DATETIME", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSetTableAdapters.DATETIMETableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DATETIMEFORM", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSetTableAdapters.TBL_DATETIMEFORMTableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DISP", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#DISP")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="LOGINTIME", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters.LOGINTIMETableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="MACADDRESS", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters.TBL_CLIENT_MACADDRESSTableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="net", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.LoggerUtility.#Setlog4netSettingPrameter(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="PSM", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#PSM")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="PSO", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#PSO")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SGM", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#SGM")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SMB", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#SMB")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SPM", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#SPM")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SSF", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#SSF")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SSM", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#SSM")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SUMMERTIMEDIFF", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSetTableAdapters.SUMMERTIMEDIFFTableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TBL", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters.TBL_CLIENT_IPTableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TBL", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters.TBL_CLIENT_MACADDRESSTableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TBL", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSetTableAdapters.TBL_DATETIMEFORMTableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TEC", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Operation.#TEC")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TIMEDIFF", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSetTableAdapters.TIMEDIFFTableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="USERINFO", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters.USERINFOTableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="USERINFO", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSetTableAdapters.USERINFOTableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="USERS", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.UsersDataSetTableAdapters.USERSTableAdapter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId:="Login", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.EnvironmentSetting.#LoginUrl")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId:="Login", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.Logger.#ContextKeyLoginId")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId:="Login", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.LoggerUtility.#ContextKeyLoginId")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.ConnectionManager.#OpenConnection(Toyota.eCRB.SystemFrameworks.Core.DBQueryTarget)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:SQL クエリのセキュリティ脆弱性を確認", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.DBQuery.#CommandText")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Users.#GetUser(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Users.#GetAllUser(System.String,System.String,System.Collections.Generic.List`1<System.Decimal>,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.SystemEnvSetting.#GetSystemEnvSetting(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.OperationType.#GetOperationType(System.String,System.Decimal,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.OperationType.#GetAllOperationType(System.String,System.Collections.Generic.List`1<System.Decimal>,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.FunctionSetting.#GetiCROPFunctionSetting(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.FunctionSetting.#GetDelaerFunctionSetting(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.DealerEnvSetting.#GetSpecificEnvSetting(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.DealerEnvSetting.#GetCommonEnvSetting(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Dealer.#GetDealer(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Dealer.#GetAllDealer(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.BranchEnvSetting.#GetSpecificEnvSetting(System.String,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Branch.#GetBranch(System.String,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.Branch.#GetAllBranch(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.WordResourceManager.#GetTitleData(System.String,System.String)")> 
''CA1709
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.UsersDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemSharedDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemEnvSettingDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.OperationTypeDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.IcropWordDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.FunctionSettingDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DlrEnvSettingDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DealerDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchListDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters")> 
''自動生成
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSet+TBL_DATETIMEFORMDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchDataSet+BRANCHDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchListDataSet+BranchTableDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DealerDataSet+DEALERDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DlrEnvSettingDataSet+DLRENVSETTINGDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.FunctionSettingDataSet+FUNCTIONSETTINGDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.IcropWordDataSet+IcropWordTableDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.OperationTypeDataSet+OPERATIONTYPEDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSet+SUMMERTIMEDIFFDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSet+TIMEDIFFDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSet+USERINFODataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemEnvSettingDataSet+SYSTEMENVSETTINGDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_MACADDRESSDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_IPDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_IPRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_MACADDRESSRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSet+TBL_DATETIMEFORMDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSet+TBL_DATETIMEFORMRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CLIENT", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_IPDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CLIENT", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_IPRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CLIENT", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_MACADDRESSDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CLIENT", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_MACADDRESSRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DATETIME", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSet+DATETIMEDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DATETIME", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSet+DATETIMERow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DATETIMEFORM", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSet+TBL_DATETIMEFORMDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DATETIMEFORM", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSet+TBL_DATETIMEFORMRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DEALER", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DealerDataSet+DEALERDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DEALER", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DealerDataSet+DEALERRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DLRENVSETTING", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DlrEnvSettingDataSet+DLRENVSETTINGDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DLRENVSETTING", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DlrEnvSettingDataSet+DLRENVSETTINGRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="FUNCTIONSETTING", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.FunctionSettingDataSet+FUNCTIONSETTINGDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="FUNCTIONSETTING", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.FunctionSettingDataSet+FUNCTIONSETTINGRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="LOGINTIME", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+LOGINTIMEDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="LOGINTIME", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+LOGINTIMERow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="MACADDRESS", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_MACADDRESSDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="MACADDRESS", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_MACADDRESSRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="OPERATIONTYPE", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.OperationTypeDataSet+OPERATIONTYPEDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="OPERATIONTYPE", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.OperationTypeDataSet+OPERATIONTYPERow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SUMMERTIMEDIFF", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSet+SUMMERTIMEDIFFDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SUMMERTIMEDIFF", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSet+SUMMERTIMEDIFFRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SUMMERTIMEDIFF", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSet+SUMMERTIMEDIFFDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SUMMERTIMEDIFF", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSet+SUMMERTIMEDIFFRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SYSTEMENVSETTING", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemEnvSettingDataSet+SYSTEMENVSETTINGDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SYSTEMENVSETTING", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemEnvSettingDataSet+SYSTEMENVSETTINGRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TBL", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_IPDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TBL", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_IPRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TBL", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_MACADDRESSDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TBL", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_MACADDRESSRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TBL", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSet+TBL_DATETIMEFORMDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TBL", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSet+TBL_DATETIMEFORMRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TIMEDIFF", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSet+TIMEDIFFDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TIMEDIFF", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSet+TIMEDIFFRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TIMEDIFF", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSet+TIMEDIFFDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TIMEDIFF", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSet+TIMEDIFFRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="USERINFO", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSet+USERINFODataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="USERINFO", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSet+USERINFORow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="USERS", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.UsersDataSet+USERSDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="USERS", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.UsersDataSet+USERSRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemSharedDataSet+DateTimeFormTableDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.UsersDataSet+USERSDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.UsersDataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemSharedDataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemEnvSettingDataSet+SYSTEMENVSETTINGDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemEnvSettingDataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSet+USERINFODataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSet+TIMEDIFFDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSet+SUMMERTIMEDIFFDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.OperationTypeDataSet+OPERATIONTYPEDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.OperationTypeDataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.IcropWordDataSet+IcropWordTableDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.IcropWordDataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.FunctionSettingDataSet+FUNCTIONSETTINGDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.FunctionSettingDataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DlrEnvSettingDataSet+DLRENVSETTINGDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DlrEnvSettingDataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DealerDataSet+DEALERDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DealerDataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSet+TBL_DATETIMEFORMDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSet+TIMEDIFFDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSet+SUMMERTIMEDIFFDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSet+DATETIMEDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchListDataSet+BranchTableDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchListDataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchDataSet+BRANCHDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchDataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_MACADDRESSDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+TBL_CLIENT_IPDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet+LOGINTIMEDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSet")> 
''CA1709
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.UsersDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemEnvSettingDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.OperationTypeDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.FunctionSettingDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DlrEnvSettingDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DealerDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemEnvSettingDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.UsersDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.OperationTypeDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.FunctionSettingDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DlrEnvSettingDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DealerDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.UsersDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemEnvSettingDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.OperationTypeDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DlrEnvSettingDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DealerDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.UsersDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemEnvSettingDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.OperationTypeDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DlrEnvSettingDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DealerDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.FunctionSettingDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.FunctionSettingDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemSharedDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.IcropWordDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchListDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.SystemConfigurationType.#iCROPConnectionString")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.DBQueryTarget.#iCROP")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemSharedDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.IcropWordDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchListDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemSharedDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.IcropWordDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchListDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.SystemConfigurationType.#iCROPConnectionString")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic.FunctionSetting.#GetiCROPFunctionSetting(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="member", Target:="Toyota.eCRB.SystemFrameworks.Core.DBQueryTarget.#iCROP")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.SystemSharedDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.StaffContextDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.IcropWordDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeFormDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.DateTimeDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchListDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.BranchDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess.AuthenticationManagerDataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.DataAccess")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core.iCROP.BizLogic")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.SystemFrameworks.Core")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB")> 

