'
'
' このファイルは、このプロジェクトに適用される SuppressMessage 
'属性を保持するために、コード分析によって使用されます。
' プロジェクト レベルの抑制には、ターゲットがないものと、特定のターゲット
'が指定され、名前空間、型、メンバーなどをスコープとするものがあります。
'
' このファイルに抑制を追加するには、[エラー一覧] でメッセージを
'右クリックし、[メッセージの非表示] をポイントして、
'[プロジェクト抑制ファイル内] をクリックします。
' このファイルに手動で抑制を追加する必要はありません。

''ASPコントロールに対するエラーのため
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_commonmasterpagesmall_master.#__BuildControl__control6()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_commonmasterpagesmall_master.#__BuildControl__control5()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_commonmasterpagesmall_master.#__BuildControl__control4()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_commonmasterpagesmall_master.#__BuildControl__control3()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_commonmasterpagesmall_master.#__BuildControl__control2()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control8()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control20()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control19()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control18()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control17()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control15()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control14()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control13()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_noheadermasterpagesmall_master.#__BuildControl__control5()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_noheadermasterpagesmall_master.#__BuildControl__control4()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_noheadermasterpagesmall_master.#__BuildControl__control3()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_noheadermasterpagesmall_master.#__BuildControl__control2()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control10()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control11()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control12()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control9()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control2()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control3()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control4()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control5()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control6()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_commonmasterpage_master.#__BuildControl__control7()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_noheadermasterpage_master.#__BuildControl__control2()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_noheadermasterpage_master.#__BuildControl__control3()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_noheadermasterpage_master.#__BuildControl__control4()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.master_noheadermasterpage_master.#__BuildControl__control5()")> 
''サンプルコードのため
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.SystemFrameworks.Web.Controls.CustomButton.set_Text(System.String)", Scope:="member", Target:="ASP.masterpagetest_aspx.#__BuildControlreloadContextMenuCustomButton()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.SystemFrameworks.Web.Controls.CustomButton.set_Text(System.String)", Scope:="member", Target:="ASP.masterpagetest_aspx.#__BuildControlupdatePresenceCustomButton()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId:="commonMaster", Scope:="member", Target:="MasterPageTest.#DeclareCommonMasterContextMenu(Toyota.eCRB.SystemFrameworks.Web.CommonMasterPage)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="operation", Scope:="member", Target:="MasterPageTest.#operationItemSelector_SelectedIndexChanged(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId:="System.Int32.ToString", Scope:="member", Target:="MasterPageTest.#Page_Load(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId:="System.String.Format(System.String,System.Object,System.Object)", Scope:="member", Target:="MasterPageTest.#Page_Load(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.#ctor(System.String,System.String)", Scope:="member", Target:="MasterPageTest.#Page_Load(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.SystemFrameworks.Web.CommonMasterContextMenuItem.set_Text(System.String)", Scope:="member", Target:="MasterPageTest.#Page_Load(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="reload", Scope:="member", Target:="MasterPageTest.#reloadContextMenuCustomButton_Click(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="MasterPageTest.#tcvButton_Click(System.Object,Toyota.eCRB.SystemFrameworks.Web.CommonMasterFooterButtonClickEventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="update", Scope:="member", Target:="MasterPageTest.#updatePresenceCustomButton_Click(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId:="System.Int32.ToString", Scope:="member", Target:="MasterPageTest.#updatePresenceCustomButton_Click(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="0", Scope:="member", Target:="ASP.ApplicationBrowserCapabilitiesFactory.#PopulateBrowserElements(System.Collections.IDictionary)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="0", Scope:="member", Target:="ASP.ApplicationBrowserCapabilitiesFactory.#PopulateMatchedHeaders(System.Collections.IDictionary)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="1", Scope:="member", Target:="Pages_ControlsSample.#customRepeater1_ClientCallback(System.Object,Toyota.eCRB.SystemFrameworks.Web.Controls.ClientCallbackEventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="0", Scope:="member", Target:="Pages_ControlsSample.#RaiseCallbackEvent(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId:="headers", Scope:="member", Target:="ASP.ApplicationBrowserCapabilitiesFactory.#WebkitmobileProcess(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="pop", Scope:="member", Target:="Pages_ControlsSample.#popOver1HeaderButton1_Click(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.Button.set_Text(System.String)", Scope:="member", Target:="ASP.masterpagetest_aspx.#__BuildControlButton2()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.Button.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControlpopOver2Trigger()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.Button.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControlpopOverForm3Trigger()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.Button.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControlpopOver1HeaderButton4()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.Button.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControlpopOver1HeaderButton3()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.Button.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControlpopOver1HeaderButton2()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.Button.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControlpopOver1HeaderButton1()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.Button.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControlButton2()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.Button.set_Text(System.String)", Scope:="member", Target:="ASP.masterpagetest_aspx.#__BuildControlTEE()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.TextBox.set_Text(System.String)", Scope:="member", Target:="Pages_ControlsSample.#Page_Load(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="custom", Scope:="member", Target:="Pages_ControlsSample.#customRepeater1_ClientCallback(System.Object,Toyota.eCRB.SystemFrameworks.Web.Controls.ClientCallbackEventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="custom", Scope:="member", Target:="Pages_ControlsSample.#customTextBox1_TextChanged(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="numeric", Scope:="member", Target:="Pages_ControlsSample.#numericBox1_ValueChanged(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TEE", Scope:="member", Target:="MasterPageTest.#TEE_Click(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.Button.set_Text(System.String)", Scope:="member", Target:="ASP.masterpagetest_aspx.#__BuildControlButton1()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Pages_ControlsSample.#Page_Load(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control17()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control16()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId:="Login", Scope:="type", Target:="Login")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="segmented", Scope:="member", Target:="Pages_ControlsSample.#segmentedButton2_SelectedIndexChanged(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="repeater", Scope:="member", Target:="Pages_ControlsSample.#popOverForm2_1_repeater_ItemDataBound(System.Object,System.Web.UI.WebControls.RepeaterItemEventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="pop", Scope:="member", Target:="Pages_ControlsSample.#popOverForm2_1_repeater_ItemDataBound(System.Object,System.Web.UI.WebControls.RepeaterItemEventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="pop", Scope:="member", Target:="Pages_ControlsSample.#popOverForm1_ClientCallback(System.Object,Toyota.eCRB.SystemFrameworks.Web.Controls.ClientCallbackEventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="dialog", Scope:="member", Target:="Pages_ControlsSample.#dialogButton_Click(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="custom", Scope:="member", Target:="Pages_ControlsSample.#customButton2_Click(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId:="commonMaster", Scope:="member", Target:="MasterPageTest.#DeclareCommonMasterFooter(Toyota.eCRB.SystemFrameworks.Web.CommonMasterPage,Toyota.eCRB.SystemFrameworks.Web.FooterMenuCategory&)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1306:SetLocaleForDataTypes", Scope:="member", Target:="Pages_ControlsSample.#Page_Load(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.#ctor(System.String,System.String)", Scope:="member", Target:="Pages_ControlsSample.#Page_Load(System.Object,System.EventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="1", Scope:="member", Target:="Pages_ControlsSample.#popOverForm1_ClientCallback(System.Object,Toyota.eCRB.SystemFrameworks.Web.Controls.ClientCallbackEventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="1", Scope:="member", Target:="Pages_ControlsSample.#popOverForm2_1_repeater_ItemDataBound(System.Object,System.Web.UI.WebControls.RepeaterItemEventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control10()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control10()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control11()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control11()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control12()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control12()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control13()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control13()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control3()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control3()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control4()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control4()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control5()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control5()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control6()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control6()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control7()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control7()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control9()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.ListItem.set_Value(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControl__control9()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.TextBox.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControldetailTextBox()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.Button.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControldialogButton()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.Button.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControlInnerButton()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.Button.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControlpopOverButton1()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.Button.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControlpopOverButton2()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="System.Web.UI.WebControls.Button.set_Text(System.String)", Scope:="member", Target:="ASP.controlssample_aspx.#__BuildControlpopupTrigger()")> 

