'
'
' このファイルは、このプロジェクトに適用される SuppressMessage 
'属性を保持するために、コード分析によって使用されます。
' プロジェクト レベルの抑制には、ターゲットがないものと、特定のターゲット
'が指定され、名前空間、型、メンバーなどをスコープとするものがあります。
'
' このファイルに抑制を追加するには、[エラー一覧] でメッセージを
'右クリックし、[メッセージの非表示] をポイントして、
'[プロジェクト抑制ファイル内] をクリックします。
' このファイルに手動で抑制を追加する必要はありません。

<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId:="System.Int64.ToString", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetVisitCount(System.String,System.String,System.Decimal)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId:="storeCode", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetVisitCount(System.String,System.String,System.Decimal)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId:="dealerCode", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetVisitCount(System.String,System.String,System.Decimal)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="Un", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#UpdateUnNecessary(System.Int64,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetVisitorCustomer(System.Int64,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="2", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetStaffNoticeRequest(System.Int64,System.String,System.Collections.Generic.List`1<System.String>)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetStaffNoticeRequest(System.Int64,System.String,System.Collections.Generic.List`1<System.String>)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="5", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetNoticeRequests(System.String,System.String,System.DateTime,System.DateTime,System.String,System.Collections.Generic.List`1<System.String>)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetNoticeRequests(System.String,System.String,System.DateTime,System.DateTime,System.String,System.Collections.Generic.List`1<System.String>)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+VisitReceptionVisitorLinkingDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+VisitReceptionVisitorLinkingCountDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+VisitReceptionVisitorCustomerDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+VisitReceptionVisitCountDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+VisitReceptionStaffNoticeRequestDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+VisitReceptionNoticeRequestsDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+VisitReceptionClaimInfoDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+SC3100101StaffStatusDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+SC3100101ReceptionInfoDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+SC3100101BordCountDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+SC3100101BoardInfoDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+SC3100101AfterOrderProcessIconInfoDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#DeleteRequestNotice(System.Int64,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetAfterOrderProcessIcon(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetAssessmentCount(System.String,System.String,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetClaimInfo(System.String,System.String,System.DateTime,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetConclusionCount(System.String,System.String,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetDeliverlyCount(System.String,System.String,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetEstimateCount(System.String,System.String,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetNoticeRequests(System.String,System.String,System.DateTime,System.DateTime,System.String,System.Collections.Generic.List`1<System.String>)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetSalesCount(System.String,System.String,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetSalesInfo(System.String,System.String,System.String,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetSalesStuffInfo(System.String,System.String,System.String,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetSalesTableUse(System.String,System.String,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetStaffNoticeRequest(System.Int64,System.String,System.Collections.Generic.List`1<System.String>)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetStaffStandby(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetVisitCount(System.String,System.String,System.Decimal)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetVisitCustCount(System.String,System.String,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetVisitorCustomer(System.Int64,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#GetVisitorLinkingCount(System.String,System.String,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#InsertRequestNotice(System.Int64,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#UpdateBroadcast(System.Int64,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#UpdateDealStaffCode(System.Int64,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#UpdateSalesTableNo(System.Int64,System.Int32,System.Int32,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#UpdateTentativeName(System.Int64,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#UpdateUnNecessary(System.Int64,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope:="member", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters.SC3100101TableAdapter.#UpdateVisitorCancel(System.Int64,System.String)")> 
'0293-0294 KN Nakamura
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101.SC3100101DataSet+SC3100101VisitorCustomerDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101.SC3100101DataSet+SC3100101VisitorSituationDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101.SC3100101DataSet+SC3100101VisitorCountDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101.SC3100101DataSet+SC3100101StandbyStaffDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101.SC3100101DataSet+SC3100101StaffSituationDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101.SC3100101DataSet+SC3100101SalesTableUseDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101.SC3100101DataSet+SC3100101ResultCountDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101.SC3100101DataSet+SC3100101ConclusionCountDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101.SC3100101DataSet+SC3100101BoardInfoDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101.SC3100101DataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101.SC3100101DataSet+SC3100101LinkingCancelDataTable")> 
'0005 KN Nakamura
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101.SC3100101DataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101.SC3100101DataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101")> 
'0004 KN Nakamura
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101.SC3100101DataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101")> 

'0004-009 TMEJ Okamura
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+SC3100101SalesTableUseDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+SC3100101StandbyStaffDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+SC3100101LinkingCancelDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess")> 

'0293 TMEJ Okamura
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+SC3100101StandbyStaffDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+SC3100101SalesTableUseDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet+SC3100101LinkingCancelDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Visit.ReceptionistMain.DataAccess.SC3100101DataSet")> 
