'
'
' このファイルは、このプロジェクトに適用される SuppressMessage 
'属性を保持するために、コード分析によって使用されます。
' プロジェクト レベルの抑制には、ターゲットがないものと、特定のターゲット
'が指定され、名前空間、型、メンバーなどをスコープとするものがあります。
'
' このファイルに抑制を追加するには、[エラー一覧] でメッセージを
'右クリックし、[メッセージの非表示] をポイントして、
'[プロジェクト抑制ファイル内] をクリックします。
' このファイルに手動で抑制を追加する必要はありません。

'0004 TCS Fujii
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.Tool.Message.DataAccess")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSetTableAdapters")> 
'0005 TCS Fujii
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.Tool.Message.DataAccess")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSetTableAdapters")> 
'0006 TCS Fujii
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.Tool.Message.DataAccess")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSetTableAdapters")> 
'0008 TCS Fujii
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB")> 
'0009 TCS Fujii
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP")> 
'0010 TCS Fujii
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e")> 
'0011 TCS Fujii
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i")> 
'0014 TCS Fujii<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SYSTEM", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#SYSTEM")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1003:UseGenericEventHandlerInstances", Scope:="type", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRowChangeEventHandler")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope:="type", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRowChangeEventHandler")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope:="type", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRowChangeEvent")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TITLE", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#TITLE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TIMELIMIT", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#TIMELIMIT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#SYSTEM")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#STRCD")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="STRCD", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#STRCD")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SYSTEM", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#SetSYSTEMNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="STRCD", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#SetSTRCDNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DLRCD", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#SetDLRCDNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACCOUNT", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#SetACCOUNTNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="MESSAGE", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#MESSAGE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SYSTEM", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#IsSYSTEMNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="STRCD", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#IsSTRCDNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DLRCD", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#IsDLRCDNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACCOUNT", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#IsACCOUNTNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#DLRCD")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DLRCD", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#DLRCD")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#ACCOUNT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACCOUNT", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoRow.#ACCOUNT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TITLE", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#TITLEColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TIMELIMIT", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#TIMELIMITColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SYSTEM", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#SYSTEMColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="STRCD", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#STRCDColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="0", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#OnRowDeleting(System.Data.DataRowChangeEventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="0", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#OnRowDeleted(System.Data.DataRowChangeEventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="0", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#OnRowChanging(System.Data.DataRowChangeEventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="0", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#OnRowChanged(System.Data.DataRowChangeEventArgs)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="MESSAGE", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#MESSAGEColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="0", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DLRCD", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#DLRCDColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TITLE", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#AddSC3040101MessageInfoRow(System.String,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TIMELIMIT", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#AddSC3040101MessageInfoRow(System.String,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SYSTEM", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#AddSC3040101MessageInfoRow(System.String,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="STRCD", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#AddSC3040101MessageInfoRow(System.String,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="MESSAGE", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#AddSC3040101MessageInfoRow(System.String,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="DLRCD", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#AddSC3040101MessageInfoRow(System.String,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACCOUNT", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#AddSC3040101MessageInfoRow(System.String,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACCOUNT", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#ACCOUNTColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable.#.ctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope:="type", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet+SC3040101MessageInfoDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet.#ReadXmlSerializable(System.Xml.XmlReader)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="0", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet.#GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet.#GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet.#GetSchemaSerializable()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:パブリック メソッドの引数の検証", MessageId:="0", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet.#.ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet.#.ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2236:CallBaseClassMethodsOnISerializableTypes", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet.#.ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope:="member", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet.#.ctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Tool.Message.DataAccess.SC3040101DataSet")> 

