' このファイルは、このプロジェクトに適用される SuppressMessage 
'属性を保持するために、コード分析によって使用されます。
' プロジェクト レベルの抑制には、ターゲットがないものと、特定のターゲット
'が指定され、名前空間、型、メンバーなどをスコープとするものがあります。
'
' このファイルに抑制を追加するには、[エラー一覧] でメッセージを
'右クリックし、[メッセージの非表示] をポイントして、
'[プロジェクト抑制ファイル内] をクリックします。
' このファイルに手動で抑制を追加する必要はありません。

<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203ModelNameDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203ExteriorColorDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080202ModelNameDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#UpdateFllwupboxSales(System.String,System.String,System.Int64,System.String,System.DateTime,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="seqno", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#UpdateFllwupboxSales(System.String,System.String,System.Int64,System.String,System.DateTime,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203PreferredCarDataTable")> 

'0015 TCS Takahashi
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203LatestActTimeDataTable")> 
'0226 TCS Takahashi
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#InsertNewCustFllwupbox(System.String,System.String,System.Int64,System.DateTime,System.String,System.DateTime,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.Nullable`1<System.DateTime>,System.String,System.String,System.Nullable`1<System.DateTime>,System.Nullable`1<System.DateTime>,System.Int64,System.String,System.String,System.String,System.String,System.DateTime,System.DateTime,System.String,System.String,System.String)")> 
'0225
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#InsertFllwupboxRslt(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.Nullable`1<System.Int32>,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int32>)")> 
'0227 TCS Takahashi
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#InsertFllwupboxRslt(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.Nullable`1<System.Int32>,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int32>)")> 
'0015 TCS Takahashi
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203StatusDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203FllwupboxSalesDataTable")> 
'0226 TCS Takahashi
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#InsertFllwupbox(System.String,System.String,System.Int64,System.DateTime,System.String,System.DateTime,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.DateTime>,System.String,System.String,System.Nullable`1<System.DateTime>,System.Nullable`1<System.DateTime>,System.Int64,System.String,System.String,System.String,System.String,System.DateTime,System.DateTime,System.String,System.String,System.String,System.String,System.String)")> 
'0220 TCS Takahashi
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#InsertFllwupboxRslt(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.Nullable`1<System.Int32>,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int32>)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#UpdateFllwupbox(System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#UpdateFLRequest(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String)")> 
'0005 TCS Takahashi
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="insert", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#insertFllwupboxMilehis(System.String,System.String,System.Int64,System.String,System.String,System.Int64,System.String,System.Double,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#GetNewVclID(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#GetNewCustID(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="Cr", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#InserActHisFllwCrHis(System.String,System.String,System.Int64,System.Nullable`1<System.Int64>,System.String,System.Int64,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.DateTime,System.String,System.String,System.String,System.String,System.String,System.Int64,System.Int64,System.String,System.String,System.String,System.Int64,System.Int64)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTSELECTTOWALK", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTSELECTTOWALK")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTSELECTTOPROC", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTSELECTTOPROC")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTSELECTTOHOT", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTSELECTTOHOT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPWALKIN", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTFLLWUPWALKIN")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPREQUEST", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTFLLWUPREQUEST")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPREPUCHASE", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTFLLWUPREPUCHASE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPPROSPECT", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTFLLWUPPROSPECT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPPROMOTION", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTFLLWUPPROMOTION")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPPERIODICAL", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTFLLWUPPERIODICAL")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPHOT", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTFLLWUPHOT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCUSTSEGMENTNEWCSTOMER", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTCUSTSEGMENTNEWCSTOMER")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCUSTSEGMENTCUSTOMER", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTCUSTSEGMENTCUSTOMER")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCUSTOMERCLASSOWNER", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTCUSTOMERCLASSOWNER")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCRACTRSLTSUCCESS", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTCRACTRSLTSUCCESS")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCRACTRSLTPROSPECT", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTCRACTRSLTPROSPECT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCRACTRSLTHOT", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTCRACTRSLTHOT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCRACTRSLTGIVEUP", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTCRACTRSLTGIVEUP")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCRACTRSLTCONTINUE", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#CONSTCRACTRSLTCONTINUE")> 
'0013 TCS Takahashi
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#GetSeqWalkInPersonWalkInId()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#GetSeqTotalhisSeqno()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#GetSeqNewcustomerVclreSeqno()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#GetSeqNewcustomerCstId()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#GetSeqInreserveInfoInreserveId()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#GetNoCompetitionMakermaster()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#GetNextActContact()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#GetFollowContact()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#GetDateFormat()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#GetCompetitorMaster()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#GetCompetitionMakermaster()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203TableAdapter.#GetActContact()")> 
'0226 TCS Kawara
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#InsertNewCustFllwupbox(System.String,System.String,System.Int64,System.DateTime,System.String,System.DateTime,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.Nullable`1<System.DateTime>,System.String,System.String,System.Nullable`1<System.DateTime>,System.Nullable`1<System.DateTime>,System.Int64,System.String,System.String,System.String,System.String,System.DateTime,System.DateTime,System.String,System.String,System.String)")> 
'0225 TCS Kawara
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#InsertFllwupboxRslt(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.Nullable`1<System.Int32>,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.String,System.String,System.String)")> 
'0224 TCS Kawara
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#InsertFllwupbox(System.String,System.String,System.Int64,System.DateTime,System.String,System.DateTime,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.DateTime>,System.String,System.String,System.Nullable`1<System.DateTime>,System.Nullable`1<System.DateTime>,System.Int64,System.String,System.String,System.String,System.String,System.DateTime,System.DateTime,System.String,System.String,System.String,System.String,System.String)")> 
'0220 TCS Kawara
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#InsertFllwupboxRslt(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.Nullable`1<System.Int32>,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.String,System.String,System.String)")> 
'0227 TCS Kawara
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#InsertFllwupboxRslt(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.Nullable`1<System.Int32>,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.String,System.String,System.String)")> 
'0310-312 TCS Kawara
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#UpdateFLRequest(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#UpdateFllwupbox(System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#InsertFllwupboxRslt(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.Nullable`1<System.Int32>,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.String,System.String)")> 
'0015 TCS Kawara
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203CompetitionDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203WinclassDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203VinDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203UsersDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203TodoColorDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203SubCategoryDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203ServiceStaffDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203ServiceMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203SeriesDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203SequenceDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203SeqDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203SelectSeriesDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203SelectedCarNumDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203RegistDataDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203OperationDayDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203NextActContactDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203NewVclIDDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203NewCustIDDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203NameTitleDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203ItitialDataDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203GetContactNmDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203FollowContactDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203FllwupboxrsltDoneDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203FllwupboxRsltDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203FllwupBoxDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203FllwSeriesDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203FllwModelDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203FllwColorDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203DlrStrFollwDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203DlrStrDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203DateFormatDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203CountDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203ContentWordDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203ContentIconPathDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203CompetitorMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203CompetitorMaster2DataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203CompetitionMakermasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203AlarmMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203ActivityFollowDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203ActivityContentDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203ActHisSelCarDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203ActHisFllwDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203ActHisContentDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203ActContactDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080201ServiceHisDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080201MileageHisDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080201MakernameDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080201FollowStatusDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080201DlrvinDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet")> 
'0005 TCS Kawara
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="insert", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#insertFllwupboxMilehis(System.String,System.String,System.Int64,System.String,System.String,System.Int64,System.String,System.Double,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="Cr", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#InserActHisFllwCrHis(System.String,System.String,System.Int64,System.Nullable`1<System.Int64>,System.String,System.Int64,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.DateTime,System.String,System.String,System.String,System.String,System.String,System.Int64,System.Int64,System.String,System.String,System.String,System.Int64,System.Int64)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203NewVclIDRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203NewVclIDDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203NewCustIDRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203NewCustIDDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#GetNewVclID(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#GetNewCustID(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="id", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#InserActHisFllwCrHis(System.String,System.String,System.Int64,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.Int64,System.String,System.String,System.String,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="series", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#InserActHisFllwCrHis(System.String,System.String,System.Int64,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.Int64,System.String,System.String,System.String,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="seqno", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#InserActHisFllwCrHis(System.String,System.String,System.Int64,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.Int64,System.String,System.String,System.String,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="Nm", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203GetContactNmRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="Nm", Scope:="type", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSet+SC3080203GetContactNmDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="nm", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#InserActHisFllwTotalHis(System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="name", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#InserActHisFllwCrHis(System.String,System.String,System.Int64,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.Int64,System.String,System.String,System.String,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="insert", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#insertFllwupboxMilehis(System.String,System.String,System.Int64,System.String,System.String,System.Int64,System.String,System.Int64,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ex", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#InserActHisFllwCrHis(System.String,System.String,System.Int64,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.Int64,System.String,System.String,System.String,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="Cr", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#InserActHisFllwCrHis(System.String,System.String,System.Int64,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.Int64,System.String,System.String,System.String,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTSELECTTOWALK", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTSELECTTOWALK")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTSELECTTOPROC", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTSELECTTOPROC")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTSELECTTOHOT", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTSELECTTOHOT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPWALKIN", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTFLLWUPWALKIN")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPREQUEST", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTFLLWUPREQUEST")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPREPUCHASE", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTFLLWUPREPUCHASE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPPROSPECT", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTFLLWUPPROSPECT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPPROMOTION", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTFLLWUPPROMOTION")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPPERIODICAL", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTFLLWUPPERIODICAL")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPHOT", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTFLLWUPHOT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCUSTSEGMENTNEWCSTOMER", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTCUSTSEGMENTNEWCSTOMER")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCUSTSEGMENTCUSTOMER", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTCUSTSEGMENTCUSTOMER")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCUSTOMERCLASSOWNER", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTCUSTOMERCLASSOWNER")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCRACTRSLTSUCCESS", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTCRACTRSLTSUCCESS")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCRACTRSLTPROSPECT", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTCRACTRSLTPROSPECT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCRACTRSLTHOT", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTCRACTRSLTHOT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCRACTRSLTGIVEUP", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTCRACTRSLTGIVEUP")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCRACTRSLTCONTINUE", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#CONSTCRACTRSLTCONTINUE")> 
'0014 TCS Kawara
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#GetNoCompetitionMakermaster()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#GetSeqWalkInPersonWalkInId()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#GetSeqTotalhisSeqno()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#GetSeqNewcustomerVclreSeqno()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#GetSeqNewcustomerCstId()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#GetSeqInreserveInfoInreserveId()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#GetNextActContact()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#GetFollowContact()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#GetDateFormat()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#GetCompetitorMaster()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#GetCompetitionMakermaster()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters.SC3080203DataTableTableAdapter.#GetActContact()")> 
'0004 TCS Kawara
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess.SC3080203DataSetTableAdapters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.CustomerInfo.Details.DataAccess")> 
