
'
'
' このファイルは、このプロジェクトに適用される SuppressMessage 
'属性を保持するために、コード分析によって使用されます。
' プロジェクト レベルの抑制には、ターゲットがないものと、特定のターゲット
'が指定され、名前空間、型、メンバーなどをスコープとするものがあります。
'
' このファイルに抑制を追加するには、[エラー一覧] でメッセージを
'右クリックし、[メッセージの非表示] をポイントして、
'[プロジェクト抑制ファイル内] をクリックします。
' このファイルに手動で抑制を追加する必要はありません。





<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#SendPushChiefTechnician(System.String,System.Decimal)")> 
'1207,1506,1507,1508,1619 TMEJ成澤
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#StartWork(System.String,System.String,System.Decimal,System.Decimal,System.String,System.Int64,System.String,System.Boolean,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetReserveChipData(System.Decimal,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#FinishWork(System.String,System.String,System.Decimal,System.Decimal,System.String,System.String,System.Boolean,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#SuspendWork(System.String,System.String,System.Decimal,System.Decimal,System.String,System.String,System.Int64,System.Boolean,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#StartWork(System.String,System.String,System.Decimal,System.Decimal,System.String,System.Int64,System.String,System.Boolean,System.Boolean)")> 
'1617,1618,1619,1620 TMEJ成澤
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#NoticeMainProcessing(System.String,System.String,System.String,Toyota.eCRB.SystemFrameworks.Web.StaffContext)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetReserveChipData(System.Int32,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#FinishWork(System.String,System.String,System.Int64,System.Int32,System.String,System.String,System.Boolean,System.Boolean)")> 
'1505-1509 TMEJ成澤
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#SuspendWork(System.String,System.String,System.Int64,System.Int32,System.String,System.String,System.Int64,System.Boolean,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#SuspendWork(System.String,System.String,System.Int64,System.Int32,System.String,System.String,System.Int64,System.Boolean,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#StartWork(System.String,System.String,System.Decimal,System.Decimal,System.String,System.Int64,System.String,System.Boolean,System.Boolean,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#StartWork(System.String,System.String,System.Int64,System.Int32,System.String,System.Int64,System.String,System.Boolean,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#FinishWork(System.String,System.String,System.Int64,System.Int32,System.String,System.Int64,System.String,System.Boolean,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#FinishWork(System.String,System.String,System.Decimal,System.Decimal,System.String,System.Int64,System.String,System.Boolean,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="Tc", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetTcStatusStandTime")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#StartWork(System.String,System.String,System.Int64,System.Int32,System.String,System.Int64,System.String,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#StartWork(System.String,System.String,System.Int64,System.Int32,System.String,System.Int64,System.String,System.Boolean)")> 
'1207-1210 KN 西田
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#UpdateStallReserveInfoData(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSetTableAdapters.SC3150101StallInfoDataTableAdapter,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallReserveInfoDataTable,System.DateTime,System.DateTime,System.Int32,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#UpdateStallReserveData(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSetTableAdapters.SC3150101StallInfoDataTableAdapter,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallReserveInfoDataTable,System.DateTime,System.String,System.Int32,System.String,System.String,System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#UpdateStallProcessInfoData(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSetTableAdapters.SC3150101StallInfoDataTableAdapter,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallProcessInfoDataTable,System.DateTime,System.DateTime,System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#UpdateStallProcessData(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSetTableAdapters.SC3150101StallInfoDataTableAdapter,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallProcessInfoDataTable,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallReserveInfoDataTable,System.DateTime,System.DateTime,System.Decimal,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#UpdateStaffStallData(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSetTableAdapters.SC3150101StallInfoDataTableAdapter,System.Int32,System.Int32,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#SuspendWork(System.String,System.String,System.Int32,System.Int32,System.String,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#StartWork(System.String,System.String,System.Int32,System.Int32,System.String,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#MoveCollisionChip(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallReserveListDataTable,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallTimeInfoDataTable,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallBreakInfoDataTable,System.String,System.String,System.Int32,System.Int32,System.DateTime,System.DateTime,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#IsStallStaffCount(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSetTableAdapters.SC3150101StallInfoDataTableAdapter,System.String,System.String,System.DateTime,System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#InsertStallProcessInfoData(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSetTableAdapters.SC3150101StallInfoDataTableAdapter,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallProcessInfoDataTable,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#InsertStaffStallData(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSetTableAdapters.SC3150101StallInfoDataTableAdapter,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallTimeInfoDataTable,System.DateTime,System.Int32,System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetTotalEndTime(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallBreakListDataTable,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetTotalEndTime(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallBreakListDataTable,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetStallBreakList(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallTimeInfoDataTable,System.String,System.String,System.Int32,System.DateTime,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetNextWorkDate(System.String,System.String,System.Int32,System.DateTime,System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetEndTimeAfterRevison(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallTimeInfoDataTable,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallBreakListDataTable,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallBreakListDataTable,System.String,System.String,System.Int32,System.Int32,System.DateTime,System.DateTime,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetEndTimeAfterRevison(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallTimeInfoDataTable,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallBreakListDataTable,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallBreakListDataTable,System.String,System.String,System.Int32,System.Int32,System.DateTime,System.DateTime,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetChipTimeList(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallBreakInfoDataTable,System.Collections.Generic.List`1<Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallReserveListRow>,System.DateTime)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#UpdateAllReserve(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallReserveListDataTable,System.Int32,System.String,System.String,System.Int32,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#ReorderReserveChildNo(System.String,System.String,System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#HHMMTextToDateTime(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetNextWorkDate(System.String,System.String,System.Int32,System.DateTime,System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#DecisionOperationTime(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallReserveInfoDataTable,System.DateTime,System.TimeSpan,System.TimeSpan)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:ローカライズされるパラメーターとしてリテラルを渡さない", MessageId:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.OutputLog(System.String,System.String,System.String,System.Exception,System.String[])", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#CheckMultiStarts(System.Int32,System.DateTime,System.TimeSpan,System.TimeSpan)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetBelongStallData()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope:="type", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i", Scope:="namespace", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP", Scope:="namespace", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101")> 
'0881 KN tsuruta[2000]
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#StartWork(System.String,System.String,System.Int32,System.Int32,System.String,System.Boolean)")> 


'0900 KN tsuruta[2000]
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#SuspendWork(System.String,System.String,System.Int32,System.Int32,System.String,System.Boolean)")> 

'0876 KN tsuruta[2000]
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetStallBreakList(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallTimeInfoDataTable,System.String,System.String,System.Decimal,System.DateTime,System.DateTime)")> 

'0875 KN tsuruta[2000]
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#SimulateChipPutting(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallTimeInfoDataTable,System.String,System.String,System.Int32,System.DateTime,System.DateTime,System.Int32,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#SimulateChipPutting(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallTimeInfoDataTable,System.String,System.String,System.Decimal,System.DateTime,System.DateTime,System.Int32,System.Boolean)")> 

'0873,0874 KN tsuruta[2201]
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetEndTimeAfterRevison(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallTimeInfoDataTable,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallBreakListDataTable,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallBreakListDataTable,System.String,System.String,System.Decimal,System.Int32,System.DateTime,System.DateTime,System.Boolean)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetNextWorkDate(System.String,System.String,System.Decimal,System.DateTime,System.Int32)")> 

'0868 KN tsuruta[2000]
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#MoveReserveSub(Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallReserveListDataTable,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallTimeInfoDataTable,Toyota.eCRB.iCROP.DataAccess.SC3150101.SC3150101DataSet+SC3150101StallBreakInfoDataTable,System.String,System.String,System.Int32,System.Int32,System.DateTime,System.DateTime)")> 

'0865 KN tsuruta[2000]
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#GetResultChipData(System.Int32,System.DateTime,System.DateTime)")> 

'1207 KN morishita
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#StartWork(System.String,System.String,System.Int64,System.Int32,System.String,System.String,System.Boolean)")> 
'1208 KN morishita
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#StartWork(System.String,System.String,System.Int64,System.Int32,System.String,System.String,System.Boolean)")> 
'1209 KN morishita
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#SuspendWork(System.String,System.String,System.Int64,System.Int32,System.String,System.String,System.Boolean)")> 
'1210 KN morishita
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.iCROP.BizLogic.SC3150101.SC3150101BusinessLogic.#SuspendWork(System.String,System.String,System.Int64,System.Int32,System.String,System.String,System.Boolean)")> 

