'
'
' このファイルは、このプロジェクトに適用される SuppressMessage 
'属性を保持するために、コード分析によって使用されます。
' プロジェクト レベルの抑制には、ターゲットがないものと、特定のターゲット
'が指定され、名前空間、型、メンバーなどをスコープとするものがあります。
'
' このファイルに抑制を追加するには、[エラー一覧] でメッセージを
'右クリックし、[メッセージの非表示] をポイントして、
'[プロジェクト抑制ファイル内] をクリックします。
' このファイルに手動で抑制を追加する必要はありません。


<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#InsertFllwupbox(System.String,System.String,System.Int64,System.DateTime,System.String,System.DateTime,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.DateTime>,System.String,System.String,System.Nullable`1<System.DateTime>,System.Nullable`1<System.DateTime>,System.Int64,System.String,System.String,System.String,System.String,System.DateTime,System.DateTime,System.String,System.String,System.String,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#InsertNewCustFllwupbox(System.String,System.String,System.Int64,System.DateTime,System.String,System.DateTime,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.Nullable`1<System.DateTime>,System.String,System.String,System.Nullable`1<System.DateTime>,System.Nullable`1<System.DateTime>,System.Int64,System.String,System.String,System.String,System.String,System.DateTime,System.DateTime,System.String,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#InsertFllwupboxRslt(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.Nullable`1<System.Int32>,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int32>)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#InsertFllwupboxRslt(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.Nullable`1<System.Int32>,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int32>)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#UpdateFllwupbox(System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#UpdateFLRequest(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#UpdateFllwupboxSales(System.String,System.String,System.Int64,System.String,System.DateTime,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="Nm", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetContactNmRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="Nm", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetContactNmDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoNewCustIDDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoNewCustIDRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoNewVclIDDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoNewVclIDRow")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#GetNewCustID(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ID", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#GetNewVclID(System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="Cr", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#InserActHisFllwCrHis(System.String,System.String,System.Int64,System.Nullable`1<System.Int64>,System.String,System.Int64,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.DateTime,System.String,System.String,System.String,System.String,System.String,System.Int64,System.Int64,System.String,System.String,System.String,System.Int64,System.Int64)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="insert", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#insertFllwupboxMilehis(System.String,System.String,System.Int64,System.String,System.String,System.Int64,System.String,System.Double,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="seqno", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#UpdateFllwupboxSales(System.String,System.String,System.Int64,System.String,System.DateTime,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#GetSeqNewcustomerCstId()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#GetSeqNewcustomerVclreSeqno()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#GetSeqTotalhisSeqno()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#GetSeqWalkInPersonWalkInId()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#GetSeqInreserveInfoInreserveId()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#GetDateFormat()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTSELECTTOWALK", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTSELECTTOWALK")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTSELECTTOPROC", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTSELECTTOPROC")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTSELECTTOHOT", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTSELECTTOHOT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPWALKIN", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTFLLWUPWALKIN")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPREQUEST", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTFLLWUPREQUEST")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPREPUCHASE", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTFLLWUPREPUCHASE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPPROSPECT", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTFLLWUPPROSPECT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPPROMOTION", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTFLLWUPPROMOTION")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPPERIODICAL", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTFLLWUPPERIODICAL")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTFLLWUPHOT", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTFLLWUPHOT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCUSTSEGMENTNEWCSTOMER", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTCUSTSEGMENTNEWCSTOMER")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCUSTSEGMENTCUSTOMER", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTCUSTSEGMENTCUSTOMER")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCUSTOMERCLASSOWNER", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTCUSTOMERCLASSOWNER")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCRACTRSLTSUCCESS", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTCRACTRSLTSUCCESS")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCRACTRSLTPROSPECT", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTCRACTRSLTPROSPECT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCRACTRSLTHOT", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTCRACTRSLTHOT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCRACTRSLTGIVEUP", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTCRACTRSLTGIVEUP")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CONSTCRACTRSLTCONTINUE", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#CONSTCRACTRSLTCONTINUE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#InsertFllwupboxRslt(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.Nullable`1<System.Int64>,System.Nullable`1<System.Int32>,System.Nullable`1<System.Int64>,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.String,System.String,System.String,System.Nullable`1<System.Int32>)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoNewSeqSelectedSeriesDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoEstVclInfoDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoExistSeqSelectedSeriesDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoEstimateCarDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoActAsmFlgDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+GetNewCustomerDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoSalesActiveListDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetCancelStatusDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoLatestActTimeDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoSelectedCarNumDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoFllwupboxrsltDoneDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoCompetitionDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoFllwupboxRsltDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoFllwupBoxDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoTodoColorDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetContactNmDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoNameTitleDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoActHisSelCarDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoActHisContentDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoActHisFllwDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoSubCategoryDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoServiceMasterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoServiceHisDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoMileageHisDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoVinDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoWinclassDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoServiceStaffDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoMakernameDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoSequenceDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoNewCustIDDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoNewVclIDDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetContractDateDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoSeriesDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetContractDateFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoWaitingObjectDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoWaitingObjectFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoDlrStrFollwDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoContentIconPathDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoContentWordDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoDateFormatDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoSeqDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetSelectedSeriesDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetStatusDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoCountFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoContractNoFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetProcessDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetProcessAfterDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoContractNoDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoCountDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetSelectedSeriesListToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetSelectedSeriesListFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetProcessToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetProcessFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetStatusFromDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoGetStatusToDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoRegistDataDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoFllwSeriesDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoFllwColorDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoFllwModelDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoActContactDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet+ActivityInfoUsersDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoDataSet")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#GetNewSeqSelectedSeries()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.CommonUtility.DataAccess.ActivityInfoTableAdapter.#GetEstimateCar(System.String,System.String,System.Int64,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.CommonUtility.DataAccess")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.CommonUtility.DataAccess")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.CommonUtility.DataAccess")> 
