'
'
' このファイルは、このプロジェクトに適用される SuppressMessage 
'属性を保持するために、コード分析によって使用されます。
' プロジェクト レベルの抑制には、ターゲットがないものと、特定のターゲット
'が指定され、名前空間、型、メンバーなどをスコープとするものがあります。
'
' このファイルに抑制を追加するには、[エラー一覧] でメッセージを
'右クリックし、[メッセージの非表示] をポイントして、
'[プロジェクト抑制ファイル内] をクリックします。
' このファイルに手動で抑制を追加する必要はありません。

'0004 TCS Fujii
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess")> 
'0005 TCS Fujii
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB", Scope:="namespace", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess")> 
'0006 TCS Fujii
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e", Scope:="namespace", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess")> 
'0008 TCS Fujii
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CRB")> 
'0009 TCS Fujii<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CROP")> 
'0010 TCS Fujii<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="e")> 
'0011 TCS Fujii
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="i")> 
'0014 TCS Fujii<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#TIMEDIFFERENCE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1003:UseGenericEventHandlerInstances", Scope:="type", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRowChangeEventHandler")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope:="type", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRowChangeEventHandler")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope:="type", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRowChangeEvent")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TIMEDIFFERENCE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#TIMEDIFFERENCE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SITENO")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITENO", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SITENO")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SITE_RSSURL")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SITE_RSSURL")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SITE_RSSURL")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="RSSURL", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SITE_RSSURL")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SITE_LASTUPDATE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SITE_LASTUPDATE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SITE_LASTUPDATE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="LASTUPDATE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SITE_LASTUPDATE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TIMEDIFFERENCE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SetTIMEDIFFERENCENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITENO", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SetSITENONull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SetSITE_RSSURLNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SetSITE_RSSURLNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="RSSURL", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SetSITE_RSSURLNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SetSITE_LASTUPDATENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SetSITE_LASTUPDATENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="LASTUPDATE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SetSITE_LASTUPDATENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACCOUNT", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#SetACCOUNTNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TIMEDIFFERENCE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#IsTIMEDIFFERENCENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITENO", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#IsSITENONull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#IsSITE_RSSURLNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#IsSITE_RSSURLNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="RSSURL", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#IsSITE_RSSURLNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#IsSITE_LASTUPDATENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#IsSITE_LASTUPDATENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="LASTUPDATE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#IsSITE_LASTUPDATENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACCOUNT", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#IsACCOUNTNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#ACCOUNT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACCOUNT", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoRow.#ACCOUNT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TIMEDIFFERENCE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#TIMEDIFFERENCEColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITENO", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#SITENOColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#SITE_RSSURLColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#SITE_RSSURLColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="RSSURL", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#SITE_RSSURLColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#SITE_LASTUPDATEColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#SITE_LASTUPDATEColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="LASTUPDATE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#SITE_LASTUPDATEColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#AddMC3040204RssSiteInfoRow(System.Int64,System.String,System.DateTime,System.String,System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TIMEDIFFERENCE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#AddMC3040204RssSiteInfoRow(System.Int64,System.String,System.DateTime,System.String,System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITENO", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#AddMC3040204RssSiteInfoRow(System.Int64,System.String,System.DateTime,System.String,System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#AddMC3040204RssSiteInfoRow(System.Int64,System.String,System.DateTime,System.String,System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="RSSURL", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#AddMC3040204RssSiteInfoRow(System.Int64,System.String,System.DateTime,System.String,System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="LASTUPDATE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#AddMC3040204RssSiteInfoRow(System.Int64,System.String,System.DateTime,System.String,System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACCOUNT", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#AddMC3040204RssSiteInfoRow(System.Int64,System.String,System.DateTime,System.String,System.Int32)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACCOUNT", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#ACCOUNTColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable.#.ctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssSiteInfoDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1003:UseGenericEventHandlerInstances", Scope:="type", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRowChangeEventHandler")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope:="type", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRowChangeEventHandler")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope:="type", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRowChangeEvent")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SITENO")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITENO", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SITENO")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITENO", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetSITENONull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetITEM_URLNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="URL", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetITEM_URLNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetITEM_URLNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetITEM_TITLENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TITLE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetITEM_TITLENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetITEM_TITLENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetITEM_SELECTNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SELECT", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetITEM_SELECTNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetITEM_SELECTNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetITEM_CREATEDATENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetITEM_CREATEDATENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CREATEDATE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetITEM_CREATEDATENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetITEM_CATEGORYNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetITEM_CATEGORYNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CATEGORY", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetITEM_CATEGORYNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACCOUNT", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#SetACCOUNTNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_URL")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_URL")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="URL", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_URL")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_URL")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_TITLE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_TITLE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TITLE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_TITLE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_TITLE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_SELECT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_SELECT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SELECT", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_SELECT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_SELECT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_CREATEDATE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_CREATEDATE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_CREATEDATE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CREATEDATE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_CREATEDATE")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_CATEGORY")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_CATEGORY")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_CATEGORY")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CATEGORY", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ITEM_CATEGORY")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITENO", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsSITENONull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsITEM_URLNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="URL", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsITEM_URLNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsITEM_URLNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsITEM_TITLENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TITLE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsITEM_TITLENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsITEM_TITLENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsITEM_SELECTNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SELECT", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsITEM_SELECTNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsITEM_SELECTNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsITEM_CREATEDATENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsITEM_CREATEDATENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CREATEDATE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsITEM_CREATEDATENull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsITEM_CATEGORYNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsITEM_CATEGORYNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CATEGORY", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsITEM_CATEGORYNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACCOUNT", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#IsACCOUNTNull()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ACCOUNT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACCOUNT", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemRow.#ACCOUNT")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITENO", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#SITENOColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ITEM_URLColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="URL", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ITEM_URLColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ITEM_URLColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ITEM_TITLEColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TITLE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ITEM_TITLEColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ITEM_TITLEColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ITEM_SELECTColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SELECT", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ITEM_SELECTColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ITEM_SELECTColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ITEM_CREATEDATEColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ITEM_CREATEDATEColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CREATEDATE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ITEM_CREATEDATEColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ITEM_CATEGORYColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ITEM_CATEGORYColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CATEGORY", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ITEM_CATEGORYColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId:="2#", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#AddMC3040204RssItemRow(System.Int64,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#AddMC3040204RssItemRow(System.Int64,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="URL", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#AddMC3040204RssItemRow(System.Int64,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="TITLE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#AddMC3040204RssItemRow(System.Int64,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SITENO", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#AddMC3040204RssItemRow(System.Int64,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="SELECT", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#AddMC3040204RssItemRow(System.Int64,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ITEM", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#AddMC3040204RssItemRow(System.Int64,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CREATEDATE", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#AddMC3040204RssItemRow(System.Int64,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="CATEGORY", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#AddMC3040204RssItemRow(System.Int64,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACCOUNT", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#AddMC3040204RssItemRow(System.Int64,System.String,System.String,System.String,System.DateTime,System.String,System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId:="ACCOUNT", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#ACCOUNTColumn")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable.#.ctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet+MC3040204RssItemDataTable")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet.#ReadXmlSerializable(System.Xml.XmlReader)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet.#GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet.#GetSchemaSerializable()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet.#.ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2236:CallBaseClassMethodsOnISerializableTypes", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet.#.ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope:="member", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet.#.ctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope:="type", Target:="Toyota.eCRB.Tool.Rss.Batch.DataAccess.MC3040204DataSet")> 
